### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by danterob** [DSpeckhals/python-indent#17]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 14.04.4
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package, v0.4.1
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/roberto/.atom/packages/python-indent/lib/python-indent.coffee:224

TypeError: Cannot read property '0' of undefined
    at PythonIndent.module.exports.PythonIndent.parseLines (/home/roberto/.atom/packages/python-indent/lib/python-indent.coffee:224:65)
    at PythonIndent.module.exports.PythonIndent.properlyIndent (/home/roberto/.atom/packages/python-indent/lib/python-indent.coffee:24:20)
    at atom-text-editor.subscriptions.add.atom.commands.add.editor:newline (/home/roberto/.atom/packages/python-indent/lib/main.coffee:17:97)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:05.0 vim-mode:move-right (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:04.7.0 vim-mode:move-down (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:04.5.0 vim-mode:move-right (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:03.7.0 vim-mode:activate-insert-mode (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
 33x -0:03.4.0 core:move-right (atom-text-editor.editor.is-focused.vim-mode.insert-mode)
     -0:00.8.0 editor:newline (atom-text-editor.editor.is-focused.vim-mode.insert-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  },
  "python-indent": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v1.7.0
linter, v1.11.3
linter-flake8, v1.13.0
minimap, v4.20.0
monokai-seti, v0.7.0
odoo-snippets, v0.3.0
project-manager, v2.7.6
python-autopep8, v0.1.3
python-indent, v0.4.1
seti-ui, v0.9.1
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by DSpeckhals** [comment]
I can reproduce this by simply typing the following, then entering a new line:

``` python
class DoesThisFail )
```

This error is caused by the Python source not being well-formed, and this package does not handle those situations gracefully. I'll see what I can do to make these instances not throw an error.

**Comment by DSpeckhals** [comment]
I fixed the issue, and published the patch. Thanks for letting me know!

**Comment by danterob** [comment]
Thank you Dustin.
