### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by quqiuzhu** [DSpeckhals/python-indent#26]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/xshare/.atom/packages/python-indent/lib/python-indent.coffee:178

TypeError: Cannot read property 'length' of undefined
    at PythonIndent.module.exports.PythonIndent.parseLines (/Users/xshare/.atom/packages/python-indent/lib/python-indent.coffee:178:20)
    at PythonIndent.module.exports.PythonIndent.properlyIndent (/Users/xshare/.atom/packages/python-indent/lib/python-indent.coffee:24:20)
    at atom-text-editor.subscriptions.add.atom.commands.add.editor:newline (/Users/xshare/.atom/packages/python-indent/lib/main.coffee:17:97)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:02.3.0 editor:newline (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
     -0:00.5.0 core:undo (atom-text-editor.editor.vim-mode.power-mode.insert-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-beautify, v0.29.7
atom-ctags, v4.5.2
auto-update-packages, v1.0.1
autocomplete-clang, v0.9.3
autocomplete-python, v1.8.1
clipboard-plus, v0.5.1
color-picker, v2.1.1
emmet, v2.4.3
environment, v1.2.0
file-icons, v1.7.14
hyperclick, v0.0.36
language-latex, v0.6.1
language-lisp, v0.2.0
language-vue, v0.14.0
linter, v1.11.8
merge-conflicts, v1.4.4
minimap, v4.24.4
pigments, v0.29.2
python-autopep8, v0.1.3
python-indent, v0.4.3
python-tools, v0.6.7
rst-preview, v1.3.1
tornado-templates, v0.2.0
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
vim-mode-visual-block, v0.2.15
vue-autocomplete, v0.1.0

# Dev
No dev packages
```

**Comment by kbrose** [comment]
@quqiuzhu Can you share some code that re-produces the issue? I have not seen this before.

**Comment by quqiuzhu** [comment]
@kbrose hey, the scripts ends with \t instead of \n each line, i copy it from Windows and edit it on Mac

**Comment by DSpeckhals** [comment]
@quqiuzhu This is pretty confusing to me. Tab is not a valid line break in anything I've heard of. I think line breaks either have to be `\n` (Unix-type) or `\r\n` (Windows), though there are some ancient edge cases.

I can reproduce this error with the following test case:

``` coffeescript
it 'indents after open def params with Windows line breaks', ->
        editor.insertText 'def test(param_a, param_b, param_c,\t'
        pythonIndent.properlyIndent()
        expect(buffer.lineForRow 1).toBe ' '.repeat 9
```

The problem is that I can only produce this in code, not with the actual editor. I don't how the `newline` event could have possibly fired with a `\t`.

Maybe someone could enlighten me a bit here...

**Comment by DSpeckhals** [comment]
I haven't heard anything else about this, so I'm closing...
