### ISSUE TITLE
Failed to activate after udate to atom 1.16.0-beta0

### ISSUE THREAD

**Issue by Evpok** [DSpeckhals/python-indent#33]
**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package 1.0.0

### Stack Trace

Failed to activate the python-indent package

```
At Cannot set property 'pythonIndent' of undefined

TypeError: Cannot set property 'pythonIndent' of undefined
  at Object.activate (/packages/python-indent/lib/main.js:25:32)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:826:28

```

### Commands

```
     -0:43.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.theme-gazizza-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
autocomplete-emojis 2.5.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.60 
colorful-json 1.1.0 
custom-title 1.0.1 
dash 1.7.1 
date 1.2.2 
fancy-bracket-matcher 1.0.1 
file-icons 2.0.17 
focus-light 1.1.0 
foldingtext-markdown 1.3.2 
ForLatex 0.1.0 
gazizza-syntax 0.2.6 
git-control 0.8.2 
git-log 0.4.1 
git-time-machine 1.5.6 
graphviz-preview 1.7.0 
html-entities 0.4.0 
Hydrogen 1.6.0 
hydrogen-launcher 1.2.0 
indent-guide-improved 1.4.12 
isotope-light-ui 2.2.7 
itg-light-syntax 0.4.0 
kuali-light-syntax 1.1.0 
language-bnf 1.1.0 
language-cython 0.3.0 
language-diff 0.7.0 
language-dot 1.6.0 
language-latex 1.0.0 
language-lua 0.9.11 
language-matlab-octave 0.1.2 
language-pfm 0.82.0 
latex 0.42.3 
latex-autocomplete 1.0.0 
latex-completions 0.3.2 
linter 1.11.23 
linter-chktex 1.3.0 
linter-coffeescript 1.0.0 
linter-eslint 8.1.3 
linter-lua 1.0.2 
linter-pylama 0.8.13 
MagicPython 1.0.7 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-themeable-pdf 1.2.0 
material 2.2.0 
material-design-syntax 1.8.0 
material-syntax 0.6.1 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-titles 1.10.0 
monokai-light 0.4.1 
naturerainbow-light-syntax 0.1.1 
naturezen-light-syntax 0.1.0 
new-era-light-syntax 0.3.1 
one-o-eight-syntax 0.25.3 
open-recent 5.0.0 
paper-flat-ui 1.3.6 
pdf-view 0.55.0 
pen-paper-coffee-syntax 0.14.9 
piatto-light 2.0.2 
platformio-ide-terminal 2.4.0 
python-indent 1.0.0 
release-notes 0.53.0 
show-origin 0.2.0 
snow-light-syntax 0.2.0 
sync-settings 0.8.1 
terminal-plus 0.14.5 
tree-view-git-branch 0.1.2 
underline-trailing-whitespace 1.4.2 
up2date 0.1.2 
```

**Comment by DSpeckhals** [comment]
I will check out the beta version and see what might be happening here. Right now, it's not obvious what is happening, but hopefully I can reproduce the problem.

**Comment by DSpeckhals** [comment]
Okay, I can reproduce the issue. I'll see what's going on and send out a fix soon.
