### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by satishmohan** [DSpeckhals/python-indent#39]
[Enter steps to reproduce:]

1. Hit Enter in commit message area after typing some text in the Git Dock Panel.

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package 1.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/satish/.atom/packages/python-indent/lib/python-indent.js:9

TypeError: Cannot read property 'getGrammar' of undefined
    at PythonIndent.indent (/packages/python-indent/lib/python-indent.js:9:24)
    at /packages/python-indent/lib/main.js:23:57)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -6:37.8.0 core:save (input.hidden-input)
     -6:36.5.0 platformio-ide-terminal:focus (input.hidden-input)
     -6:28.7.0 platformio-ide-terminal:paste (textarea.)
     -6:21.8.0 core:save (input.hidden-input)
     -6:20.8.0 platformio-ide-terminal:focus (input.hidden-input)
     -6:13.9.0 platformio-ide-terminal:prev (textarea.)
  2x -6:12.6.0 platformio-ide-terminal:next (textarea.)
     -6:10.9.0 platformio-ide-terminal:prev (textarea.)
     -6:10.1.0 platformio-ide-terminal:next (textarea.)
     -0:38.6.0 core:confirm (div.github-StagingView.unstaged-changes-focused)
     -0:29 docblockr:parse-enter (input.hidden-input)
     -0:29 editor:newline (input.hidden-input)
     -0:09.6.0 core:move-up (input.hidden-input)
     -0:09.0 editor:move-to-end-of-line (input.hidden-input)
     -0:06.4.0 docblockr:parse-enter (input.hidden-input)
     -0:06.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-ctags 5.1.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
center-line 1.2.4 
ctags-status 1.3.7 
docblockr 0.10.3 
file-icons 2.1.6 
highlight-selected 0.13.1 
incremental-search 5.2.2 
intentions 1.1.2 
linter 2.1.4 
linter-flake8 2.2.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
move-by-paragraph 2.0.1 
move-panes 0.2.0 
platformio-ide-terminal 2.5.1 
project-manager 3.3.4 
python-autopep8 0.1.3 
python-indent 1.0.2 
python-tools 0.6.9 
spacegray-atom-dark-syntax 1.3.2 
split-diff 1.4.0 
sync-settings 0.8.1 
tasks 2.6.6 
todo-show 1.11.0 
```

**Comment by DSpeckhals** [comment]
It looks like this has to do with Atom's new dock feature. This is simple to fix. I'll get on it soon.
