### ISSUE TITLE
Uncaught TypeError: Cannot read property 'transact' of undefined

### ISSUE THREAD

**Issue by TDHolmes** [DSpeckhals/python-indent#56]
[Enter steps to reproduce:]

This is at least what I was doing, not sure if it reproduces 100%...

1. code in python
2. create a branch
3. Add the modified file and start typing a commit message

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package 1.1.3

### Stack Trace

Uncaught TypeError: Cannot read property 'transact' of undefined

```
At /Users/tylerholmes/.atom/packages/python-indent/lib/python-indent.js:12

TypeError: Cannot read property 'transact' of undefined
    at PythonIndent.indent (/packages/python-indent/lib/python-indent.js:12:45)
    at HTMLElement.editorNewline (/packages/python-indent/lib/main.js:23:57)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -2:28.8.0 core:backspace (input.hidden-input)
     -2:27.4.0 core:save (input.hidden-input)
     -2:26.9.0 core:backspace (input.hidden-input)
     -2:26.4.0 core:save (input.hidden-input)
     -2:15 editor:newline (input.hidden-input)
     -2:12.2.0 core:backspace (input.hidden-input)
     -2:09.2.0 core:move-left (input.hidden-input)
     -2:09.0 editor:newline (input.hidden-input)
     -2:06.1.0 core:backspace (input.hidden-input)
     -2:05.4.0 core:save (input.hidden-input)
     -1:49.4.0 core:backspace (input.hidden-input)
     -1:48.4.0 core:save (input.hidden-input)
     -1:11.2.0 autocomplete-plus:confirm (input.hidden-input)
     -1:10.9.0 core:save (input.hidden-input)
  3x -0:23.3.0 core:backspace (input.hidden-input)
  2x -0:06.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.4 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
copy-as-rtf 0.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-cmake 0.3.0 
language-restructuredtext 1.1.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-flake8 2.2.1 
linter-json-lint 0.1.2 
linter-ui-default 1.6.10 
python-indent 1.1.3 
rest-client 1.3.1 
todo-show 2.1.0 
```

**Comment by TDHolmes** [comment]
I just recently updated to the new release (1.1.3)

**Comment by DSpeckhals** [comment]
Thanks for filling the issue. I think I know what caused this, and will get a fix out shortly.
