### ISSUE TITLE
Uncaught TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by kinteriq** [DSpeckhals/python-indent#76]
Steps made:
1. pulled files from git repository;
2. hit 'Undo' last commit;
3. started rewriting a commit message;
4. hit 'enter' to go to the next line of this commit message.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [python-indent](https://github.com/DSpeckhals/python-indent) package 1.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'search' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'search' of undefined
    at indentationLevel (/packages/python-indent/node_modules/python-indent-parser/lib/index.js:11:17)
    at nextIndentationLevel (/packages/python-indent/node_modules/python-indent-parser/lib/index.js:47:16)
    at Object.indentationInfo (/packages/python-indent/node_modules/python-indent-parser/lib/index.js:15:22)
    at /packages/python-indent/lib/main.js:42:66
    at Array.forEach (<anonymous>)
    at /packages/python-indent/lib/main.js:33:43
    at TextBuffer.transact (/usr/share/atom/resources/app/static/<embedded>:11:491299)
    at TextEditor.transact (/usr/share/atom/resources/app/static/<embedded>:11:24215)
    at HTMLElement.indent (/packages/python-indent/lib/main.js:31:12)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -0:23.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
python-autopep8 0.1.3 
python-indent 1.2.3 
python-tools 0.6.9 
python-yapf 0.14.0 
script 3.18.1 
vim-mode-plus 1.36.0 
```

**Comment by DSpeckhals** [comment]
I can't seem to reproduce this. Have you experienced this problem any other times?

**Comment by kinteriq** [comment]
I haven't encountered it since that day. Tried to recreate it today, everything works fine.
